image: adoptopenjdk/openjdk12:alpine

stages:
  - build
  - check
  - publish

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/

cache:
  untracked: true
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - "*/build"

build:
  stage: build
  script:
    - ./gradlew build -x check
  artifacts:
    paths:
      - "*/build/libs/*.jar"
    expire_in: 1 week

check:
  stage: check
  script:
    - ./gradlew check
  artifacts:
    reports:
      junit: "*/build/test-results/test/TEST-*.xml"
    expire_in: 1 week

bintray upload:
  stage: publish
  script:
    - ./gradlew -Pversion=$CI_COMMIT_TAG bintrayUpload
    - ls */build/libs/*.jar
  only:
    - tags

gradle plugin publish:
  stage: publish
  script:
    - ./gradlew publishPlugins -Pversion=$CI_COMMIT_TAG -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
    - ls */build/libs/*.jar
  only:
    - tags