image: adoptopenjdk/openjdk12:alpine

stages:
  - build
  - deploy

before_script:
  - echo `pwd`
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - rm -f  .gradle/caches/modules-2/modules-2.lock
  - rm -fr .gradle/caches/*/plugin-resolution/

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - "*/build"

build and check:
  stage: build
  script:
    - ./gradlew build check
  artifacts:
    paths:
      - "*/build/libs/*.jar"
    reports:
      junit: "*/build/test-results/test/TEST-*.xml"
    expire_in: 1 week

bintray upload:
  stage: publish
  script:
    - ./gradlew -Pversion=$CI_COMMIT_TAG bintrayUpload
  only:
    - tags

gradle plugin publish:
  stage: publish
  script:
    - ./gradlew publishPlugins -Pversion=$CI_COMMIT_TAG -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
  only:
    - tags